set -g prefix ^q

# set-option -g default-terminal 'screen-256color'
# set-option -g terminal-overrides ',xterm-256color:RGB'

set -g base-index 1
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
# set -g mouse on
set-window-option -g mode-keys vi

set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'alexanderjeurissen/tmux-world-clock'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

#set -g status-left '%Y-%m-%d %H:%M #{tmux_mode_indicator}'
# set -g status-left '#{prefix_highlight} | %a %Y-%m-%d %H:%M'
set -g @catppuccin_flavour 'mocha' # latte,frappe, macchiato or mocha
set -g @catppuccin_status_modules_left "session application"
set -g @catppuccin_status_modules_right "directory date_time"
# set -g @catppuccin_directory_text "#{pane_current_path}"

set -g @world_clock_tz 'America/Los_Angeles'
set-option -g status-right "#[bg=blue, fg=black]#{world_clock_status}"

# source-file ~/.config/tmux/rose_pine.conf

bind -r m resize-pane -Z

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

run '~/.config/tmux/plugins/tpm/tpm'
