
[[grape]]
import = "grapes/finn/prelude"

[[grape]]
import = "grapes/finn/zsh-startup"

[[grape]]
import = "bun"
from = "grapes"

[[grape]]
import = "grapes/fnm"

[[grape]]
import = "grapes/fzf"

[[grape]]
import = "go"
from = "grapes"

[[grape]]
import = "starship"
from = "grapes"

[[grape]]
import = "grapes/television"

[[grape]]
import = "grapes/finn/eza-ext"

[[grape]]
import = "grapes/finn/fav"

[[grape]]
import = "grapes/finn/fd-ext"

[[grape]]
import = "grapes/finn/isolde"

[[grape]]
import = "grapes/finn/nvim-ext"

[[grape]]
import = "grapes/finn/yazi-ext"

# zoxide must be the last one
[[grape]]
import = "grapes/zoxide"