[[grape]]
import = "bun"
from = "grapes"

[[grape]]
import = "grapes/fnm"

[[grape]]
import = "grapes/fzf"

[[grape]]
import = "go"
from = "grapes"

[[grape]]
import = "starship"
from = "grapes"


# zoxide must be the last one
[[grape]]
import = "grapes/zoxide"